<a href="https://colab.research.google.com/github/FurkanAhmed2/NLP/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install tensorflow

In [3]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

**One Hot Representation**

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[461, 386, 396, 361], [461, 386, 396, 52], [461, 57, 396, 120], [280, 384, 344, 102, 239], [280, 384, 344, 102, 216], [486, 461, 251, 396, 131], [244, 292, 147, 102]]


**Word Embedding Represntation**

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 461 386 396 361]
 [  0   0   0   0 461 386 396  52]
 [  0   0   0   0 461  57 396 120]
 [  0   0   0 280 384 344 102 239]
 [  0   0   0 280 384 344 102 216]
 [  0   0   0 486 461 251 396 131]
 [  0   0   0   0 244 292 147 102]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 461, 386, 396, 361], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 151ms/step


array([[-0.03389844, -0.02361201, -0.03163394, -0.00176014, -0.04648435,
        -0.02908915, -0.00371819, -0.04097742,  0.00837346,  0.04405787],
       [-0.03389844, -0.02361201, -0.03163394, -0.00176014, -0.04648435,
        -0.02908915, -0.00371819, -0.04097742,  0.00837346,  0.04405787],
       [-0.03389844, -0.02361201, -0.03163394, -0.00176014, -0.04648435,
        -0.02908915, -0.00371819, -0.04097742,  0.00837346,  0.04405787],
       [-0.03389844, -0.02361201, -0.03163394, -0.00176014, -0.04648435,
        -0.02908915, -0.00371819, -0.04097742,  0.00837346,  0.04405787],
       [ 0.00715983,  0.01444845, -0.00252952,  0.03946844,  0.00954012,
         0.03710802,  0.04221532,  0.02534019, -0.01721159,  0.0431549 ],
       [-0.03379339, -0.01617091,  0.02547068, -0.02477738, -0.04144464,
         0.00156355, -0.02955568, -0.04989513, -0.01884838, -0.00111379],
       [ 0.04177752, -0.01899176,  0.03082721, -0.0485253 , -0.02711705,
        -0.04024839,  0.04774994,  0.01669003

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 52ms/step
[[[-0.03389844 -0.02361201 -0.03163394 -0.00176014 -0.04648435
   -0.02908915 -0.00371819 -0.04097742  0.00837346  0.04405787]
  [-0.03389844 -0.02361201 -0.03163394 -0.00176014 -0.04648435
   -0.02908915 -0.00371819 -0.04097742  0.00837346  0.04405787]
  [-0.03389844 -0.02361201 -0.03163394 -0.00176014 -0.04648435
   -0.02908915 -0.00371819 -0.04097742  0.00837346  0.04405787]
  [-0.03389844 -0.02361201 -0.03163394 -0.00176014 -0.04648435
   -0.02908915 -0.00371819 -0.04097742  0.00837346  0.04405787]
  [ 0.00715983  0.01444845 -0.00252952  0.03946844  0.00954012
    0.03710802  0.04221532  0.02534019 -0.01721159  0.0431549 ]
  [-0.03379339 -0.01617091  0.02547068 -0.02477738 -0.04144464
    0.00156355 -0.02955568 -0.04989513 -0.01884838 -0.00111379]
  [ 0.04177752 -0.01899176  0.03082721 -0.0485253  -0.02711705
   -0.04024839  0.04774994  0.01669003 -0.01681668  0.01274529]
  [ 0.01552607  0.0048538   0.01680516  0.0302406  -0.01393

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 461, 386, 396, 361], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 20ms/step
[[-0.03389844 -0.02361201 -0.03163394 -0.00176014 -0.04648435 -0.02908915
  -0.00371819 -0.04097742  0.00837346  0.04405787]
 [-0.03389844 -0.02361201 -0.03163394 -0.00176014 -0.04648435 -0.02908915
  -0.00371819 -0.04097742  0.00837346  0.04405787]
 [-0.03389844 -0.02361201 -0.03163394 -0.00176014 -0.04648435 -0.02908915
  -0.00371819 -0.04097742  0.00837346  0.04405787]
 [-0.03389844 -0.02361201 -0.03163394 -0.00176014 -0.04648435 -0.02908915
  -0.00371819 -0.04097742  0.00837346  0.04405787]
 [ 0.00715983  0.01444845 -0.00252952  0.03946844  0.00954012  0.03710802
   0.04221532  0.02534019 -0.01721159  0.0431549 ]
 [-0.03379339 -0.01617091  0.02547068 -0.02477738 -0.04144464  0.00156355
  -0.02955568 -0.04989513 -0.01884838 -0.00111379]
 [ 0.04177752 -0.01899176  0.03082721 -0.0485253  -0.02711705 -0.04024839
   0.04774994  0.01669003 -0.01681668  0.01274529]
 [ 0.01552607  0.0048538   0.01680516  0.0302406  -0.01393981  0.0484574
